### ISSUE TITLE
Needed Informations

### ISSUE THREAD

**Issue by lhumke** [Smart-City-SoSe-2022/Local-Finder#1]
Hi, I need some Informations to create a docker template for your microservice.
I need following Informations:

- What programming languages are you going to use?
- What frameworks or libraries are you going to use to create your webserver, api, frontend?
- What DBMS do you want to use? MySQL, NoSQL, ...
- What IDE or text editor are you using during your development?
- Do you need to use any external APIs

**Comment by ReneBdev** [comment]
Frontend: Vue.js mit HTML, JavaScript und CSS
Backend: Flask basierend auf Python
Datenbank: postgreSQL
IDE: Visual Studio Code
External API: OpenStreetMap API
